#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "coordnet"
primary_region = "ams"
console_command = "/app/backend/manage.py shell"
kill_signal = "SIGTERM"
kill_timeout = 30
swap_size_mb = 1024

[build.args]
  BUILD_ENVIRONMENT = "production"
  SENTRY_AUTH_TOKEN = "REDACTED"
  SENTRY_DSN = "REDACTED"

[deploy]
  release_command = "bash -c '/app/backend/manage.py migrate --noinput'"
  # Add this if we switch to a CDN / cloud storage
  # && /app/backend/manage.py collectstatic --noinput'"


[env]
  USE_DOCKER="no"
  DJANGO_SETTINGS_MODULE="config.settings.production"
  DJANGO_ALLOWED_HOSTS="coordnet.fly.dev,app.coord.dev,coordnet.internal"
  DJANGO_SECURE_SSL_REDIRECT="False"  # We're using Fly's SSL termination and this breaks internal connections.
  SENTRY_ENVIRONMENT="production"
  CONN_MAX_AGE=0  # Disable persistent connections, otherwise they accumulate when using async Django
  VITE_CRDT_URL = "wss://ws.coord.dev"
  VITE_BACKEND_WS_URL = "wss://app.coord.dev"
  VITE_BACKEND_URL = "https://app.coord.dev"

[http_service]
  internal_port = 5000
  # force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 4
  processes = ["app"]


[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
  processes = ["worker"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
  processes = ["beat", "pubsub"]

[[statics]]
  guest_path = "/app/backend/staticfiles"
  url_prefix = "/assets/"

[[restart]]
  policy = "always"
  processes = ["worker", "beat", "pubsub"]

[[restart]]
  policy = "on-failure"
  retries = 10
  processes = ["app"]

[processes]
  app = "/start-production"
  worker = "/start-celeryworker-production"
  beat = "/start-celerybeat-production"
  pubsub = "/start-pubsub-listener"
